[volt_var_1]
Control1 = "VVar"
Control2 = "None"
Control3 = "None"
pf = "None"
pfMin = 0.8
pfMax = 1
Pmin = 0
Pmax = 1
uMin = 0.93
uDbMin = 0.967
uDbMax = 1.033
uMax = 1.07
QlimPU = 0.3
PFlim = 1
"Enable PF limit" = false
uMinC = 1.07
uMaxC = 1.1
PminVW = 10
VWtype = "Available Power"
"%UCutoff" = 1.1
"%PCutin" = 10
"%PCutout" = 10
Efficiency = 100
Priority = "Var"
DampCoef = 0.8

[volt_var_ieee_1547_2018_catB]
Control1 = "VVar"
Control2 = "None"
Control3 = "None"
pf = 1
pfMin = 0.8
pfMax = 1
Pmin = 0
Pmax = 1
uMin = 0.92
uDbMin = 0.98
uDbMax = 1.02
uMax = 1.08
QlimPU = 0.44
PFlim = 0.9
enable_pf_limit = false
uMinC = 1.08
uMaxC = 1.1
PminVW = 10
VWtype = "Rated Power"
percent_p_cutin = 10
percent_p_cutout = 10
Efficiency = 100
Priority = "Var"
DampCoef = 0.8

[volt_watt]
Control1 = "VW"
Control2 = "None"
Control3 = "None"
DampCoef = 0.8
PFlim = 0.9
PminVW = 20
Priority = "Watt"
QlimPU = 0.44
VWtype = "Available Power"
uMaxC = 1.1
uMinC = 1.06
